version: "3"

name: nitter-only

services:
  nitter:
    image: ghcr.io/sekai-soft/nitter:master
    # container_name: nitter
    # ports:
    #   - "8080:80"
    volumes:
      - ./nitter.conf:/src/nitter.conf:Z,ro
      - ./nitter-guest_accounts.json:/src/guest_accounts.json:Z,ro
    depends_on:
      - nitter-redis
    restart: unless-stopped
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:80 || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # network_mode: service:nitter-ts
  nitter-redis:
    image: redis:6-alpine
    # container_name: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - nitter-redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2
  nitter-auth:
    build:
      context: nitter-auth
      dockerfile: Dockerfile
    container_name: nitter-auth
    stdin_open: true
    tty: true
  nitter-guardian:
    image: nginx
    # container_name: nitter-guardian
    ports:
      - "8080:8080"
    volumes:
      - ./nitter-guardian.nginx.conf:/etc/nginx/conf.d/default.conf:Z,ro
      - ./.htpasswd:/etc/nginx/.htpasswd:Z,ro
    depends_on:
      - nitter
    restart: unless-stopped
volumes:
  nitter-redis:
